project:
  name: cfn-ps-ct-newrelic-one
  owner: quickstart@amazon.com
  package_lambda: false
tests:
  newrelic-onboarding-us-west-2:
    parameters:
      NewRelicLicenseKey: ''
      AdditionalParametersLicenseKey: ''
      NewRelicAccountNumber: ''
      LaunchAccountList: ''
      NewRelicAccessKey: ''
      StackSetName: 'NewRelic-Integration'
      StackSetUrl: 'https://cfn-ps-ct-newrelic-one.s3.us-east-2.amazonaws.com/newrelic-stack-set.yml'
    regions:
      - us-west-2
    template: templates/control-tower-customization.template.yml