AWSTemplateFormatVersion: 2010-09-09
Description: 'Installs NewRelic Infrastructure Agent in EC2 instances when template is launched or instance goes in running state. CRON job updates Infra Agent in all instances once every month. Installation logs are also sent to NewRelic. (qs-1uesekrte)'
Parameters:
  TargetEC2TagKey:
    Type: String
    Default: '*'
    Description: Tag Key associated with EC2 instance where NewRelic infrastructure agent needs to be installed. Keep it * for selecting all instances.
  TargetEC2TagValue:
      Type: String
      Default: '*'
      Description: Tag Value associated with EC2 instance where NewRelic infrastructure agent needs to be installed. Keep it * for selecting all instances.
  NewRelicInfrastructureAgent:
    Type: String
    Description: "New Relic's infrastructure monitoring agent is a lightweight executable file that collects data about your hosts. It also forwards data from our on-host integrations to New Relic, as well as log data for log analytics."
    Default: "New-Relic-infrastructure-monitoring-agent"
  InstallationType:
    Description: 'Specify the type of installation. Uninstall and resinstall -  The application is taken offline until the reinstallation process completes. In-place update -  The application is available while new or updated files are added to the installation.'
    Type: String
    Default: 'Uninstall and reinstall'
    AllowedValues:
      - 'Uninstall and reinstall'
      - 'In-place update'
  Action:
    Description: 'Specify whether or not to install or uninstall the package.'
    Type: String
    Default: 'Install'
    AllowedValues:
      - 'Install'
      - 'Uninstall'
  NewRelicLicenseKey:
    Type: String
    NoEcho: true
    Description: The license key associated with the account you wish to export metrics to
    AllowedPattern: '^[A-Za-z0-9]{40}$'
  AdditionalParametersLicenseKey:
    NoEcho: true
    AllowedPattern: '\{"SSM_NR_LICENSE_KEY": "[A-Za-z0-9]{40}"\}'
    Description: 'NewRelicLicenseKey in this format - {"SSM_NR_LICENSE_KEY": "<your_license_key>"}'
    Type: String
  NewRelicLogsEndpoint:
    Type: String
    Description: 'New Relic Logs endpoint URL. Use default unless your New Relic account uses an EU data center. See NR_LOGGING_ENDPOINT in https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/ for details.'
    Default: 'https://log-api.newrelic.com/log/v1'
    AllowedValues:
      - 'https://log-api.newrelic.com/log/v1'
      - 'https://log-api.eu.newrelic.com/log/v1'
  NewRelicInfraAgentInstallerName:
    Type: String
    Default: NewRelic-Infra-Agent-Installer
    Description: Name of SSM Association that installs latest version of NewRelic Infrastructure agent in EC2 instances once every month.

Conditions:
  TargetTaggedInstances: !And
    - !Not [!Equals [!Ref TargetEC2TagKey, "*"]]
    - !Not [!Equals [!Ref TargetEC2TagValue, "*"]]
  TargetAllInstances: !Or
    - !Equals [!Ref TargetEC2TagKey, "*"]
    - !Equals [!Ref TargetEC2TagValue, "*"]
Resources:
  NewRelicInfraAgentInstallerForTaggedInstances:
    DependsOn: SendLogsToNREndpoint
    Condition: TargetTaggedInstances
    Type: 'AWS::SSM::Association'
    Properties:
      AssociationName: !Sub "${NewRelicInfraAgentInstallerName}"
      Name: AWS-ConfigureAWSPackage
      ScheduleExpression: "rate(30 days)"
      Targets:
        - Key: !Sub "tag:${TargetEC2TagKey}"
          Values:
            - !Ref TargetEC2TagValue
      Parameters:
        action:
          - !Ref Action
        installationType:
          - !Ref InstallationType
        name:
          - !Ref NewRelicInfrastructureAgent
        additionalArguments:
          - !Ref AdditionalParametersLicenseKey

  NewRelicInfraAgentInstallerForAllInstances:
    DependsOn: SendLogsToNREndpoint
    Condition: TargetAllInstances
    Type: 'AWS::SSM::Association'
    Properties:
      AssociationName: !Sub "${NewRelicInfraAgentInstallerName}"
      Name: AWS-ConfigureAWSPackage
      ScheduleExpression: "rate(30 days)"
      Targets:
        - Key: "InstanceIds"
          Values:
            - "*"
      Parameters:
        action: 
          - !Ref Action
        installationType: 
          - !Ref InstallationType
        name: 
          - !Ref NewRelicInfrastructureAgent
        additionalArguments: 
          - !Ref AdditionalParametersLicenseKey

  NewRelicApiDestination:
    DependsOn: NewRelicConnection
    Type: AWS::Events::ApiDestination
    Properties:
      Name: NewRelic-Logs-Endpoint
      HttpMethod: POST
      InvocationEndpoint: !Ref NewRelicLogsEndpoint
      ConnectionArn: !GetAtt NewRelicConnection.Arn

  NewRelicConnection:
    Type: AWS::Events::Connection
    Properties:
      Name: NewRelic-Endpoint-Connection
      AuthorizationType: API_KEY
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: Api-Key
          ApiKeyValue: !Ref NewRelicLicenseKey
        InvocationHttpParameters: 
          HeaderParameters: 
            - Key: Api-Key
              Value: !Ref NewRelicLicenseKey
        
  EventBridgeApiDestinationPolicy:
    DependsOn: InvokeApiDestinationEventBridgeRole
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub 'NewRelic-EventBridgeApiDestinationPolicy-${AWS::Region}'
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "events:InvokeApiDestination"
            Resource:
              - !Sub 'arn:${AWS::Partition}:events:${AWS::Region}:${AWS::AccountId}:api-destination/CT-Newrelic-Logs-Endpoint/*'
      Roles:
        - !Ref InvokeApiDestinationEventBridgeRole
        
  InvokeApiDestinationEventBridgeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'NewRelic-EventBridge-Invoke-Api-Destination-${AWS::Region}'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonEventBridgeFullAccess'
        
  EventBridgeTargetDLQ:
    Type: AWS::SQS::Queue	
    Properties:
      QueueName: "NewRelic-Agent-Installation-FailedInvocations-DLQ"  
      
  SendLogsToNREndpoint:
    DependsOn: EventBridgeTargetDLQ
    Type: AWS::Events::Rule
    Properties:
      Name: NewRelic-EC2-Infra-Agent-Installations-Logs-Rule
      EventPattern:
        source:
          - "aws.ssm"
        detail-type:
          - "EC2 Command Invocation Status-change Notification"
        detail:
          status:
            - "Failed"
            - "Success"
      Targets:
        - Arn: !GetAtt NewRelicApiDestination.Arn
          Id: "Newrelic-Logs-Endpoint"
          RoleArn: !GetAtt InvokeApiDestinationEventBridgeRole.Arn
          InputTransformer:
            InputPathsMap:
              account: "$.account"
              command-id: "$.detail.command-id"
              detail-type: "$.detail-type"
              document-name: "$.detail.document-name"
              id: "$.id"
              instance-id: "$.detail.instance-id"
              region: "$.region"
              requested-date-time: "$.detail.requested-date-time"
              resources: "$.resources"
              source: "$.source"
              status: "$.detail.status"
              time: "$.time"
            InputTemplate: >
              {	
                "id": <id>,	
                "detail-type": <detail-type>,	
                "source": <source>,	
                "account": <account>,	
                "time": <time>,	
                "region": <region>,	
                "resources": <resources>,	
                "command-id": <command-id>,	
                "document-name": <document-name>,	
                "instance-id": <instance-id>,	
                "InstallationStatus": <status>,	
                "PackageName": "New-Relic-infrastructure-monitoring-agent"	
              }
          DeadLetterConfig:
            Arn: !GetAtt EventBridgeTargetDLQ.Arn
        
