AWSTemplateFormatVersion: 2010-09-09
Description: Integrates New Relic with AWS accounts that use AWS Control Tower. This deployment launches as a stack set in your AWS Control Tower landing zone.(qs-1rsulpe1p)
Parameters:
  TargetEC2TagKey:
    Type: String
    Default: '*'
    Description: Tag Key associated with EC2 instance where NewRelic infrastructure agent needs to be installed. Keep it * for selecting all instances.
  TargetEC2TagValue:
    Type: String
    Default: '*'
    Description: Tag Value associated with EC2 instance where NewRelic infrastructure agent needs to be installed. Keep it * for selecting all instances.
  NewRelicInfraAgentInstallerName:
    Type: String
    Default: CT-NewRelic-Infra-Agent-Installer
    Description: Name of SSM Association that installs latest version of NewRelic Infrastructure agent in EC2 instances once every month.
  InstallationType:
    Description: 'Specify the type of installation for new relic infrastructure package. Uninstall and resinstall -  The application is taken offline until the reinstallation process completes. In-place update -  The application is available while new or updated files are added to the installation.'
    Type: String
    Default: 'Uninstall and reinstall'
    AllowedValues:
      - 'Uninstall and reinstall'
      - 'In-place update'
  Action:
    Description: 'Specify whether or not to install or uninstall the new relic infrastructure package.'
    Type: String
    Default: 'Install'
    AllowedValues:
      - 'Install'
      - 'Uninstall'
  AdditionalParametersLicenseKey:
    Description: 'NewRelicLicenseKey in this format - {"SSM_NR_LICENSE_KEY": "<your_license_key>"}'
    Type: String
    NoEcho: true
    AllowedPattern: '\{"SSM_NR_LICENSE_KEY": "[A-Za-z0-9]{40}"\}'
  NewRelicLogsEndpoint:
    Type: String
    Description: 'New Relic Logs endpoint URL. Use default unless your New Relic account uses an EU data center. See NR_LOGGING_ENDPOINT in https://docs.newrelic.com/docs/logs/forward-logs/aws-lambda-sending-cloudwatch-logs/ for details.'
    Default: 'https://log-api.newrelic.com/log/v1'
    AllowedValues:
      - 'https://log-api.newrelic.com/log/v1'
      - 'https://log-api.eu.newrelic.com/log/v1'
  InstallNewrelicInfrastructureAgentInEc2InstancesStackURL:
    Type: String
    Default: https://aws-quickstart.s3.amazonaws.com/quickstart-ct-newrelic-one/templates/EC2_Quickstart.yml
    Description: "S3 Url of ec2 quickstart template - Installs and manages NewRelic Infrastructure Agent in ec2 instances"
  NewRelicAccountNumber:
    Type: String
    Description: New Relic account ID
    AllowedPattern: '[0-9]+'
    ConstraintDescription: New Relic account ID contains only numbers
  NewRelicLicenseKey:
    Type: String
    NoEcho: true
    Description: The license key associated with the account you wish to export metrics to
    AllowedPattern: '^[A-Za-z0-9]{40}$'
    ConstraintDescription: New Relic ingestKey is 40-character Hexadecimal String
  NewRelicDatacenter:
    Type: String
    Description: New Relic datacenter your metrics are exported to
    AllowedValues:
      - 'US'
      - 'EU'
  CloudWatchMetricsStreamingTemplateURL:
    Type: String
    Default: https://aws-quickstart.s3.amazonaws.com/quickstart-ct-newrelic-one/templates/MetricStreams_CloudFormation.yml
    Description: "S3 Url of cloudwatch metric stream template"
  CloudWatchMetricStreamName:
    Type: String
    Description: "Name of new CloudWatch Metric Stream(must be unique per AWS account in the same AWS Region)"
  FirehoseStreamName:
    Type: String
    Description: "Name of new Kinesis Firehose Delivery Stream (must be unique per AWS account in the same AWS Region)"
  S3BackupBucketName:
    Type: String
    Description: "Name of new S3 Bucket Destination for failed events (must be globally unique across all AWS accounts in all AWS Regions within a partition)"
  NewRelicTrustedPrincipal:
    Type: String
    Default: 754728514883
    Description: 'New Relic AWS Account Id for integration with customer AWS account. https://docs.newrelic.com/docs/integrations/amazon-integrations/get-started/connect-aws-new-relic-infrastructure-monitoring/'

Resources:
  CloudWatchMetricStreamsStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref CloudWatchMetricsStreamingTemplateURL
      Parameters:
        NewRelicLicenseKey: !Ref NewRelicLicenseKey
        NewRelicDatacenter: !Ref NewRelicDatacenter
        CloudWatchMetricStreamName: !Ref CloudWatchMetricStreamName
        FirehoseStreamName: !Ref FirehoseStreamName
        S3BackupBucketName: !Ref S3BackupBucketName
      TimeoutInMinutes: 10
  InstallNewrelicInfrastructureAgentInEc2InstancesStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Ref InstallNewrelicInfrastructureAgentInEc2InstancesStackURL
      Parameters:
        InstallationType: !Ref InstallationType
        Action: !Ref Action
        AdditionalParametersLicenseKey: !Ref AdditionalParametersLicenseKey
        NewRelicLogsEndpoint: !Ref NewRelicLogsEndpoint
        NewRelicLicenseKey: !Ref NewRelicLicenseKey
        NewRelicInfraAgentInstallerName: !Ref NewRelicInfraAgentInstallerName
        TargetEC2TagKey: !Ref TargetEC2TagKey
        TargetEC2TagValue: !Ref TargetEC2TagValue
      TimeoutInMinutes: 15
  NewRelicDefaultPolicyRole:
    Type: 'AWS::IAM::Role'
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W28
            reason: "New Relic must use unique IAM role names to identify them."
    Properties:
      ManagedPolicyArns: 
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/ReadOnlyAccess'
      RoleName: !Join ['_', ['NewRelicIntegrationRole', !Ref NewRelicAccountNumber]]
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub 'arn:aws:iam::${NewRelicTrustedPrincipal}:root'
            Action: 'sts:AssumeRole'
            Condition:
              StringEquals:
                'sts:ExternalId': !Ref NewRelicAccountNumber